#!/usr/bin/env python3
"""Aggregate GS Hau A2 multi-seed matrix → mean±SD and LaTeX snippets.

Reads ``results/tables/a2_multiseed_matrix.csv`` (written by
``27_a2_multiseed_matrix.py``) and exports:

* ``results/tables/a2_multiseed_summary.csv`` — one row per arm
* ``results/tables/a2_multiseed_summary.json`` — same + gate counts
* ``results/tables/a2_multiseed_latex.txt`` — copy-paste numbers for Tables 5/7

Usage:
    python scripts/28_a2_aggregate.py
    python scripts/28_a2_aggregate.py --min-seeds 5
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
MATRIX = REPO / "results" / "tables" / "a2_multiseed_matrix.csv"
OUT_CSV = REPO / "results" / "tables" / "a2_multiseed_summary.csv"
OUT_JSON = REPO / "results" / "tables" / "a2_multiseed_summary.json"
OUT_TEX = REPO / "results" / "tables" / "a2_multiseed_latex.txt"

# Arms that feed Table 7 paired-ablation rows (PASS/FAIL under val gate).
TABLE7_ARMS = {
    "p0_dt_on": "Q$\\leftarrow$KC $+\\Delta t$ (recommended)",
    "hg_qkc_on": "Q$\\leftarrow$KC on",
    "hg_qkc_off": "Q$\\leftarrow$KC off (twin)",
}

# pyKT baselines for Table 4/headline context.
BASELINE_ARMS = ("simplekt", "gikt", "akt")

VAL_GATE = 0.002


def _fmt_mean_sd(values: np.ndarray) -> str:
    if len(values) == 0:
        return "---"
    if len(values) == 1:
        return f"{values[0]:.4f}"
    return f"{values.mean():.4f}${{\\pm}}{values.std(ddof=1):.4f}"


def _gate_pass(val_on: float | None, val_twin: float | None) -> bool | None:
    if val_on is None or val_twin is None or np.isnan(val_on) or np.isnan(val_twin):
        return None
    return (val_on - val_twin) >= VAL_GATE


def aggregate(df: pd.DataFrame, min_seeds: int) -> tuple[pd.DataFrame, dict]:
    ok = df[df["status"] == "ok"].copy()
    rows: list[dict] = []
    for arm, grp in ok.groupby("arm", sort=True):
        aucs = grp["auc"].astype(float).to_numpy()
        val_aucs = grp["val_auc"].dropna().astype(float).to_numpy()
        row = {
            "arm": arm,
            "backend": grp["backend"].iloc[-1],
            "n_seeds": int(len(aucs)),
            "auc_mean": float(aucs.mean()) if len(aucs) else np.nan,
            "auc_sd": float(aucs.std(ddof=1)) if len(aucs) > 1 else 0.0,
            "val_auc_mean": float(val_aucs.mean()) if len(val_aucs) else np.nan,
            "val_auc_sd": float(val_aucs.std(ddof=1)) if len(val_aucs) > 1 else 0.0,
            "minutes_total": float(grp["minutes"].astype(float).sum()),
            "seeds_done": ",".join(str(int(s)) for s in sorted(grp["seed"].astype(int))),
            "complete": len(aucs) >= min_seeds,
        }
        rows.append(row)
    summary = pd.DataFrame(rows)

    twin_val = summary.loc[summary["arm"] == "hg_qkc_off", "val_auc_mean"]
    twin_mean = float(twin_val.iloc[0]) if len(twin_val) else np.nan
    gate_rows: list[dict] = []
    for arm in ("p0_dt_on", "hg_qkc_on"):
        sub = ok[ok["arm"] == arm]
        if sub.empty or np.isnan(twin_mean):
            continue
        passes = sub["val_auc"].astype(float) - twin_mean >= VAL_GATE
        gate_rows.append(
            {
                "arm": arm,
                "k_pass": int(passes.sum()),
                "n_seeds": int(len(passes)),
                "gate": f"{passes.sum()}/{len(passes)} PASS @ Δval≥{VAL_GATE}",
            }
        )

    payload = {
        "matrix_rows": int(len(df)),
        "ok_rows": int(len(ok)),
        "min_seeds": min_seeds,
        "val_gate": VAL_GATE,
        "twin_val_mean": twin_mean,
        "arms": summary.to_dict(orient="records"),
        "gate_counts": gate_rows,
        "latex": {},
    }
    for arm, label in TABLE7_ARMS.items():
        sub = ok[ok["arm"] == arm]
        if sub.empty:
            continue
        aucs = sub["auc"].astype(float).to_numpy()
        payload["latex"][arm] = {
            "label": label,
            "auc": _fmt_mean_sd(aucs),
            "n": int(len(aucs)),
        }
    for arm in BASELINE_ARMS:
        sub = ok[ok["arm"] == arm]
        if sub.empty:
            continue
        aucs = sub["auc"].astype(float).to_numpy()
        payload["latex"][arm] = {"auc": _fmt_mean_sd(aucs), "n": int(len(aucs))}

    return summary, payload


def _write_latex(payload: dict) -> None:
    lines = [
        "% Auto-generated by scripts/28_a2_aggregate.py — paste into Tables 5/7 when A2 complete.",
        f"% ok_rows={payload['ok_rows']} min_seeds={payload['min_seeds']}",
        "",
        "Table 7 paired-ablation AUC (test, fold 0, clean L=400):",
    ]
    for arm, spec in payload.get("latex", {}).items():
        if arm in TABLE7_ARMS:
            lines.append(f"  {spec['label']}: {spec['auc']}  (n={spec['n']} seeds)")
    lines.append("")
    lines.append("pyKT baselines (test AUC, same protocol):")
    for arm in BASELINE_ARMS:
        spec = payload.get("latex", {}).get(arm)
        if spec:
            lines.append(f"  {arm}: {spec['auc']}  (n={spec['n']} seeds)")
    lines.append("")
    for g in payload.get("gate_counts", []):
        lines.append(f"  {g['arm']}: {g['gate']}")
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_TEX.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=MATRIX)
    parser.add_argument("--min-seeds", type=int, default=5)
    args = parser.parse_args()
    if not args.input.exists():
        print(f"Missing {args.input} — run 27_a2_multiseed_matrix.py first.", file=sys.stderr)
        return 1
    df = pd.read_csv(args.input)
    summary, payload = aggregate(df, args.min_seeds)
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(OUT_CSV, index=False)
    OUT_JSON.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    _write_latex(payload)
    print(summary.to_string(index=False))
    print(f"\nWrote {OUT_CSV.relative_to(REPO)}")
    print(f"Wrote {OUT_JSON.relative_to(REPO)}")
    print(f"Wrote {OUT_TEX.relative_to(REPO)}")
    complete = summary["complete"].sum()
    print(f"\nArms with >={args.min_seeds} seeds: {complete}/{len(summary)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
